
name: CI

on:
  push:
    # tags:
    #   - '*'
jobs:
  build:
    strategy:
      matrix:
        version: [10, 12, 14]
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: write file
        run: |
         echo ${{matrix.version}} > data-${{matrix.version}}.txt
      # Runs a set of commands using the runners shell
      - name: upload artifact
        uses: actions/upload-artifact@v4
        with: 
          name: ${{matrix.version}}
          path: data-${{matrix.version}}.txt

  create_release:
    needs: build
    # if: startsWith(github.event.ref, 'refs/tags/cdm-v-')
    runs-on: ubuntu-latest
    steps:
      - name: Create subfolder
        run: mkdir artifacts_download
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: ./artifacts_download
      - name: Print files list
        run: find .
      - name: ls folder
        run: ls -la ./artifacts_download
      - name: zip artifacts_data
        run: for dir in */; do [ -d "$dir" ] && zip -r "${dir%/}.zip" "${dir%/}" && rm -r "${dir%/}"; done
      - name: Print files list
        run: find .
      - name: ls folder
        run: ls -la ./artifacts_download
      # - name: Create release
      #   uses: softprops/action-gh-release@v2
      #   with:
      #     body: Changed description
      #     draft: false
      #     prerelease: false
      #     token: ${{ secrets.GITHUB_TOKEN }}
      #     files: |
      #       ${{github.workspace}}/*/*.zip